-- Generated by LuaWatch Designer
-- Requires SimpleUI C++ implementation

currentPage = "main"

-- Persistent scroll variables
if web_content_scroll == nil then web_content_scroll = 0 end

function draw_main()
    -- button_0
    if ui.button(0, 410, 410, 30, "https://google.com", 14823) then
        currentPage = "urlenter"
    end
    -- button_1
    if ui.button(60, 445, 90, 40, "back", 10665) then
        print("Button button_1 clicked")
    end
    -- button_2
    if ui.button(155, 445, 80, 40, "reld", 10665) then
        print("Button button_2 clicked")
    end
    -- button_3
    if ui.button(240, 445, 115, 40, "menu", 14792) then
        currentPage = "quickmenu"
    end
    -- text_4
    ui.text(95, 485, "Done (150ms)", 1, 65535)
    -- List: web_content
    web_content_scroll = ui.beginList(0, 35, 410, 370, web_content_scroll, 400)
    ui.endList()

    -- text_6
    ui.text(240, 0, "100%", 2, 65535)
    -- text_7
    ui.text(90, 0, "9:42", 2, 65535)
end

function draw_quickmenu()
    -- button_0
    if ui.button(20, 100, 180, 60, "add to bm", 10665) then
        print("Button button_0 clicked")
    end
    -- button_1
    if ui.button(210, 100, 180, 60, "bookmarks", 10665) then
        print("Button button_1 clicked")
    end
    -- button_2
    if ui.button(20, 170, 180, 60, "history", 10665) then
        print("Button button_2 clicked")
    end
    -- button_3
    if ui.button(210, 170, 180, 60, "clrhistory", 10665) then
        print("Button button_3 clicked")
    end
    -- button_4
    if ui.button(30, 405, 140, 45, "exit", 59783) then
        print("Button button_4 clicked")
    end
    -- text_5
    ui.text(25, 245, "free psram:", 1, 65535)
    -- text_6
    ui.text(125, 470, "webprimitive 0.1", 1, 65535)
    -- text_7
    ui.text(25, 275, "https://google.com", 1, 65535)
    -- button_8
    if ui.button(255, 405, 120, 45, "back", 10665) then
        currentPage = "main"
    end
end

function draw_urlenter()
    -- text_0
    ui.text(10, 90, " ", 2, 65535)
    -- button_1
    if ui.button(90, 10, 105, 60, "cancel", 10665) then
        currentPage = "main"
    end
    -- button_2
    if ui.button(205, 10, 110, 60, "go", 10665) then
        print("Button button_2 clicked")
    end
    -- button_3
    if ui.button(15, 175, 120, 55, "New Element", 10665) then
        print("Button button_3 clicked")
    end
    -- button_4
    if ui.button(145, 175, 120, 55, "New Element", 10665) then
        print("Button button_4 clicked")
    end
    -- button_5
    if ui.button(275, 175, 125, 55, "New Element", 10665) then
        print("Button button_5 clicked")
    end
    -- button_6
    if ui.button(15, 305, 120, 55, "New Element", 10665) then
        print("Button button_6 clicked")
    end
    -- button_7
    if ui.button(275, 305, 125, 55, "New Element", 10665) then
        print("Button button_7 clicked")
    end
    -- button_8
    if ui.button(145, 305, 120, 55, "New Element", 10665) then
        print("Button button_8 clicked")
    end
    -- button_9
    if ui.button(145, 240, 120, 55, "New Element", 10665) then
        print("Button button_9 clicked")
    end
    -- button_10
    if ui.button(15, 240, 120, 55, "New Element", 10665) then
        print("Button button_10 clicked")
    end
    -- button_11
    if ui.button(275, 240, 125, 55, "New Element", 10665) then
        print("Button button_11 clicked")
    end
    -- button_12
    if ui.button(275, 370, 125, 55, "New Element", 10665) then
        print("Button button_12 clicked")
    end
    -- button_13
    if ui.button(145, 370, 120, 55, "New Element", 10665) then
        print("Button button_13 clicked")
    end
    -- button_14
    if ui.button(15, 370, 120, 55, "New Element", 10665) then
        print("Button button_14 clicked")
    end
end

function draw()
    ui.rect(0, 0, 410, 502, 0) -- Clear background

    if currentPage == "main" then
        draw_main()
    elseif currentPage == "quickmenu" then
        draw_quickmenu()
    elseif currentPage == "urlenter" then
        draw_urlenter()
    end
end
